//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsers
    {
        public int Usu_Id { get; set; }
        public string Usu_FullUserName { get; set; }
        public string Usu_Password { get; set; }
        public Nullable<int> Usu_UserCreate { get; set; }
        public Nullable<System.DateTime> Usu_DateCreate { get; set; }
        public Nullable<int> Usu_UserModify { get; set; }
        public Nullable<System.DateTime> Usu_DateModify { get; set; }
        public string Usu_Rol { get; set; }
    }
}
